### ISSUE TITLE
Issue with latest Arch Linux (fmt-9.0.0)

### ISSUE THREAD

**Issue by makanddream** [pervices/pvpkg#1]
Hi PerVices team,

By mistake I updated my Archlinux to the latest version, unfortunately gnuradio stopped working. After some research, on the gnu radio github there is a closed issue ([#6052](https://github.com/gnuradio/gnuradio/issues/6052)) with the fmt-9.0.0 version. This problem has been solved but I tried to rebuild gnu radio from your repository and I still have this problem. Do you think you can upgrade the gnu radio you are using or should I downgrade my Archlinux?

Equipment: Crimson TNG

Thank in advance, :smiley:
Alan.

**Comment by vmw** [comment]
Hi,

You can try the latest gnuradio archlinux package which is available here;

http://files.pervices.com/latest/sw/archlinux/gnuradio/

In addition, you can observe the latest pipeline code used to actually compile the sources here, which should allow you to compile gnuradio on the latest version of archlinux:

https://github.com/pervices/pvpkg/blob/master/Arch/GnuRadio/Dockerfile

Let me know if this helps address the issue.

**Comment by vmw** [comment]
Closing issue; if it persists, please reach out, and we can reopen it.
